title: Nerv 
lang: en
supported_langs: [en,id]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nervidn.net" # the base hostname & protocol for your site, e.g. http://example.com
site_source: "https://nervuniverse.github.io/nervweb-v2"
